//! A 5x7 bitmap font. There's no text pipeline, so each lit cell of a glyph is
//! drawn as a quad like any other geometry.

use glam::Vec2;

use super::mesh;
use crate::renderer::Vertex;

const COLS: usize = 5;
const ROWS: usize = 7;
/// Horizontal advance per character, in cells: the glyph plus one of spacing.
const ADVANCE: usize = COLS + 1;

type Glyph = [&'static str; ROWS];

/// Draws `ch` centered on `center`, `height` world units tall.
pub fn push_glyph(center: Vec2, height: f32, ch: char, color: [f32; 4], out: &mut Vec<Vertex>) {
    let cell = height / ROWS as f32;
    let top_left = center + Vec2::new(-cell * COLS as f32, height) / 2.0;
    push_glyph_cells(top_left, cell, ch, color, out);
}

/// Draws a line of text with its bottom-left corner at `origin`.
pub fn push_text(origin: Vec2, height: f32, text: &str, color: [f32; 4], out: &mut Vec<Vertex>) {
    let cell = height / ROWS as f32;
    for (i, ch) in text.chars().enumerate() {
        let top_left = origin + Vec2::new((i * ADVANCE) as f32 * cell, height);
        push_glyph_cells(top_left, cell, ch, color, out);
    }
}

/// Characters without a glyph (including space) are left blank.
fn push_glyph_cells(top_left: Vec2, cell: f32, ch: char, color: [f32; 4], out: &mut Vec<Vertex>) {
    let Some(rows) = glyph(ch) else { return };
    for (row, pattern) in rows.iter().enumerate() {
        for (col, _) in pattern.chars().enumerate().filter(|&(_, c)| c == 'X') {
            // Y points up, so each successive row sits lower.
            let min = top_left + Vec2::new(col as f32, -(row as f32 + 1.0)) * cell;
            mesh::quad(min, min + Vec2::splat(cell), color, out);
        }
    }
}

fn glyph(ch: char) -> Option<&'static Glyph> {
    GLYPHS.iter().find(|(c, _)| *c == ch).map(|(_, rows)| rows)
}

#[rustfmt::skip]
const GLYPHS: &[(char, Glyph)] = &[
    ('.', [".....", ".....", ".....", ".....", ".....", ".XX..", ".XX.."]),
    ('A', [".XXX.",
           "X...X",
           "X...X",
           "XXXXX",
           "X...X",
           "X...X",
           "X...X"]),
    ('B', ["XXXX.",
           "X...X",
           "X...X",
           "XXXX.",
           "X...X",
           "X...X",
           "XXXX."]),
    ('C', [".XXX.",
           "X...X",
           "X....",
           "X....",
           "X....",
           "X...X",
           ".XXX."]),
    ('D', ["XXX..",
           "X..X.",
           "X...X",
           "X...X",
           "X...X",
           "X..X.",
           "XXX.."]),
    ('E', ["XXXXX",
           "X....",
           "X....",
           "XXXX.",
           "X....",
           "X....",
           "XXXXX"]),
    ('F', ["XXXXX",
           "X....",
           "X....",
           "XXXX.",
           "X....",
           "X....",
           "X...."]),
    ('G', [".XXX.",
           "X...X",
           "X....",
           "X.XXX",
           "X...X",
           "X...X",
           ".XXXX"]),
    ('H', ["X...X",
           "X...X",
           "X...X",
           "XXXXX",
           "X...X",
           "X...X",
           "X...X"]),
    ('I', [".XXX.",
           "..X..",
           "..X..",
           "..X..",
           "..X..",
           "..X..",
           ".XXX."]),
    ('J', ["..XXX",
           "...X.",
           "...X.",
           "...X.",
           "...X.",
           "X..X.",
           ".XX.."]),
    ('K', ["X...X",
           "X..X.",
           "X.X..",
           "XX...",
           "X.X..",
           "X..X.",
           "X...X"]),
    ('L', ["X....",
           "X....",
           "X....",
           "X....",
           "X....",
           "X....",
           "XXXXX"]),
    ('M', ["X...X",
           "XX.XX",
           "X.X.X",
           "X...X",
           "X...X",
           "X...X",
           "X...X"]),
    ('N', ["X...X",
           "X...X",
           "XX..X",
           "X.X.X",
           "X..XX",
           "X...X",
           "X...X"]),
    ('O', [".XXX.",
           "X...X",
           "X...X",
           "X...X",
           "X...X",
           "X...X",
           ".XXX."]),
    ('P', ["XXXX.",
           "X...X",
           "X...X",
           "XXXX.",
           "X....",
           "X....",
           "X...."]),
    ('Q', [".XXX.",
           "X...X",
           "X...X",
           "X...X",
           "X.X.X",
           "X..X.",
           ".XX.X"]),
    ('R', ["XXXX.",
           "X...X",
           "X...X",
           "XXXX.",
           "X.X..",
           "X..X.",
           "X...X"]),
    ('S', [".XXX.",
           "X...X",
           "X....",
           ".XXX.",
           "....X",
           "X...X",
           ".XXX."]),
    ('T', ["XXXXX",
           "..X..",
           "..X..",
           "..X..",
           "..X..",
           "..X..",
           "..X.."]),
    ('U', ["X...X",
           "X...X",
           "X...X",
           "X...X",
           "X...X",
           "X...X",
           ".XXX."]),
    ('V', ["X...X",
           "X...X",
           "X...X",
           "X...X",
           "X...X",
           ".X.X.",
           "..X.."]),
    ('W', ["X...X",
           "X...X",
           "X...X",
           "X.X.X",
           "X.X.X",
           "X.X.X",
           ".X.X."]),
    ('X', ["X...X",
           "X...X",
           ".X.X.",
           "..X..",
           ".X.X.",
           "X...X",
           "X...X"]),
    ('Y', ["X...X",
           "X...X",
           ".X.X.",
           "..X..",
           "..X..",
           "..X..",
           "..X.."]),
    ('Z', ["XXXXX",
           "....X",
           "...X.",
           "..X..",
           ".X...",
           "X....",
           "XXXXX"]),
    ('0', [".XXX.",
           "X...X",
           "X..XX",
           "X.X.X",
           "XX..X",
           "X...X",
           ".XXX."]),
    ('1', ["..X..",
           ".XX..",
           "..X..",
           "..X..",
           "..X..",
           "..X..",
           ".XXX."]),
    ('2', [".XXX.",
           "X...X",
           "....X",
           "...X.",
           "..X..",
           ".X...",
           "XXXXX"]),
    ('3', ["XXXXX",
           "...X.",
           "..X..",
           "...X.",
           "....X",
           "X...X",
           ".XXX."]),
    ('4', ["...X.",
           "..XX.",
           ".X.X.",
           "X..X.",
           "XXXXX",
           "...X.",
           "...X."]),
    ('5', ["XXXXX",
           "X....",
           "XXXX.",
           "....X",
           "....X",
           "X...X",
           ".XXX."]),
    ('6', ["..XX.",
           ".X...",
           "X....",
           "XXXX.",
           "X...X",
           "X...X",
           ".XXX."]),
    ('7', ["XXXXX",
           "....X",
           "...X.",
           "..X..",
           ".X...",
           ".X...",
           ".X..."]),
    ('8', [".XXX.",
           "X...X",
           "X...X",
           ".XXX.",
           "X...X",
           "X...X",
           ".XXX."]),
    ('9', [".XXX.",
           "X...X",
           "X...X",
           ".XXXX",
           "....X",
           "...X.",
           ".XX.."]),
    ('+', [".....",
           "..X..",
           "..X..",
           "XXXXX",
           "..X..",
           "..X..",
           "....."]),
    ('-', [".....",
           ".....",
           ".....",
           "XXXXX",
           ".....",
           ".....",
           "....."]),
    ('%', ["XX...",
           "XX..X",
           "...X.",
           "..X..",
           ".X...",
           "X..XX",
           "...XX"]),
];
